import React from 'react';
import { Text } from 'react-native';

function FavoriteScreen() {
    return (
        <Text>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores rem unde officia laboriosam autem ratione distinctio recusandae consequatur provident facere odio, dolore accusamus dolorum velit doloribus voluptas ex molestias eveniet?
            Officia impedit hic error! Impedit eius veniam quidem, molestias accusamus esse labore, voluptas tenetur aliquam earum vitae quaerat error aspernatur nisi culpa assumenda ratione blanditiis id quas? At, fuga rem!
            Commodi quidem quas impedit optio eligendi deserunt temporibus! Quisquam autem neque illum quas fugit cupiditate officia magnam quasi maxime laudantium fugiat velit sequi unde ab animi, esse consequuntur soluta et?
            Maxime fugit nam sequi. Aliquid voluptas facilis, dolores accusamus magnam ratione suscipit culpa nemo necessitatibus, repudiandae labore. Consectetur, corporis ratione distinctio hic perferendis numquam? Temporibus quidem iusto voluptates sequi tenetur!
            Soluta quos molestias praesentium exercitationem accusamus architecto debitis modi mollitia ad veritatis deserunt quibusdam repudiandae iure, officia non excepturi! Ipsa omnis, at assumenda modi inventore perspiciatis debitis placeat aut laudantium.
            Ad enim optio debitis libero maiores dicta ipsa recusandae consequuntur voluptatem repellat sequi iure aspernatur perspiciatis, officia qui pariatur aliquid totam quaerat atque maxime aliquam dolorem! Velit in expedita mollitia!
            Blanditiis, necessitatibus! Quaerat, quasi ab. Autem quasi voluptates ea explicabo temporibus quibusdam ratione exercitationem perferendis fugit, amet tempora vero tenetur enim aliquam eius. Accusamus, sint. Animi nesciunt aperiam inventore corrupti?
            Consectetur commodi aliquam qui atque molestiae, corrupti eaque, quo voluptatem fuga nam possimus. Provident, quas soluta, eveniet nemo sed molestiae nostrum quam incidunt obcaecati eos tempora odio eligendi adipisci expedita.
            Alias nulla tenetur officiis sint eos, neque consequatur inventore rem? Porro temporibus quasi dicta quam corrupti natus architecto aliquam assumenda et doloremque eum fugiat necessitatibus, ut similique vero autem maxime.
            Culpa animi repellendus facere dolorum soluta, iure nemo nesciunt saepe obcaecati delectus non quas esse, quis voluptatibus vel blanditiis aliquam sed laborum quidem minus quia numquam aut. Harum, placeat veritatis?
            A ex cupiditate placeat quisquam harum ipsam consequatur exercitationem perferendis ad pariatur accusamus laboriosam sit neque, cumque aspernatur ab? Commodi architecto impedit placeat maiores amet, ad molestiae ullam voluptatum atque.
            Quibusdam, suscipit. Hic nobis, maxime tempora iusto consequatur eligendi nisi, illum repellendus voluptates harum unde odio minus deleniti quo similique, earum ipsum magnam reiciendis quidem! Maiores explicabo tempore atque soluta!
            Eius facilis vero veniam necessitatibus dicta libero tempora. Tenetur, eos alias temporibus fugiat perferendis repellat cum enim assumenda, itaque molestiae totam. Laudantium rerum, fuga dolor atque repellat aut beatae laborum?
            Culpa, similique? Obcaecati inventore consequatur eligendi voluptas repellendus esse at labore. Adipisci unde aliquam consequatur, culpa molestias tenetur corrupti delectus consequuntur velit repellendus minima magnam pariatur perferendis accusantium cum ipsa.
            Ducimus quaerat culpa natus tempore, sed sit magni accusantium dolor quas sequi eligendi dignissimos illo maxime excepturi delectus consequatur! At beatae non excepturi ratione expedita voluptatem ad magnam laborum molestias!
            Aliquid, quibusdam! Repudiandae corporis dolore animi dicta esse doloremque similique sequi, debitis, mollitia vel incidunt temporibus numquam culpa aut maiores eos atque eligendi amet architecto iste? Porro eveniet eum facere!
            Aliquid quibusdam, id aut distinctio ipsam impedit nam explicabo mollitia nemo atque praesentium magni veritatis doloribus eius itaque facilis dolorem! Doloremque exercitationem quos similique voluptatum, dolores officiis vero quisquam itaque.
            Corrupti, aut rem eaque atque ut quibusdam, natus quod impedit suscipit minima, fuga autem dignissimos earum eos doloremque iure eveniet provident dolorum quasi exercitationem blanditiis maxime? Nostrum modi perspiciatis blanditiis!
            Dolore aut dolores officia! Ad, veniam inventore numquam sit eum eius accusantium aspernatur facere harum tempora, distinctio, ut sapiente. Molestias dolor suscipit saepe error ipsam aut repellendus vel, nam qui!
            Sunt in consequuntur vero sint eius! Expedita quod eligendi ex blanditiis. Aut delectus modi cumque recusandae odio, adipisci aspernatur tempore voluptas repudiandae magnam, facere hic. Et dolorum non deserunt voluptate.
            Officia consectetur molestiae ad culpa inventore illum facilis veritatis aliquam assumenda odit? Inventore unde, sapiente neque iste quia fugit deleniti? Blanditiis magnam impedit consectetur deserunt minima? Non blanditiis saepe maxime!
            A beatae, ducimus labore laboriosam dignissimos consectetur quos obcaecati commodi, culpa fuga eligendi maiores. Omnis inventore voluptatum cum fugiat voluptatem ratione ex nostrum? Provident repudiandae omnis earum rem non. Magnam!
            Corrupti eum tenetur ullam in modi similique sunt, minus nobis necessitatibus iste cupiditate consectetur qui illum quo neque iusto expedita non numquam magnam quas? Similique voluptatum assumenda repudiandae odio voluptas?
            Consequuntur exercitationem reiciendis magnam odio architecto sed doloribus alias. Nostrum provident accusamus nesciunt rerum porro vel doloremque doloribus ipsam eum qui accusantium voluptates odit, totam, ullam, dolore dolorum optio asperiores!
            Reprehenderit, ratione! Facilis consectetur fuga corrupti, ipsum vel aliquid asperiores animi, quae possimus deserunt beatae. Et ad accusantium qui, amet sunt nemo autem consequatur veniam. Id libero atque aliquam rerum.
            Nemo, magnam itaque saepe aliquam voluptates, corrupti accusamus veritatis necessitatibus error libero nesciunt tenetur nihil neque aperiam omnis reprehenderit, tempore repellendus beatae. Itaque possimus facilis quibusdam autem repellat illo aperiam.
            Itaque nesciunt, sed commodi possimus ipsam voluptate, quod ex quae mollitia, beatae et ipsa veritatis nobis modi dolorum ad dolor? Adipisci quo praesentium dolor dicta voluptatum, necessitatibus harum est magnam!
            Inventore repudiandae obcaecati dolorem non aliquam! Velit accusantium reprehenderit soluta! Unde quaerat fugiat eaque illum et, temporibus sapiente sequi facilis magni. Tempore enim sequi excepturi quis modi eius repudiandae ut!
            Est esse eligendi aut quibusdam sint, eveniet perspiciatis assumenda quod nam ut molestiae! Beatae consequuntur, assumenda excepturi distinctio deleniti corrupti sunt consectetur impedit explicabo quam. Aliquam animi sapiente perspiciatis dolores.
            Totam suscipit, esse et labore saepe quos veniam? Sed, ullam placeat consequatur adipisci voluptates inventore similique voluptas saepe natus, ut sit? Iure fugiat exercitationem sapiente quas corrupti dolorum fuga autem.
            Quidem laudantium sit, blanditiis id, debitis natus unde harum voluptas asperiores dolorum, provident eum consequuntur saepe! Nisi, illum. Voluptates blanditiis provident ipsum voluptatum, qui ab cumque nostrum assumenda mollitia perferendis.
            Ullam facilis minus cupiditate temporibus quo vitae quas assumenda, et at provident sint. Harum ab aliquam fugiat labore repudiandae obcaecati, eum commodi dicta deserunt laboriosam adipisci nam distinctio qui alias?
            Officiis eos autem corporis neque debitis et modi, odit ipsa dolore vero illo optio! Dolores repudiandae deleniti, dolore laborum culpa vero quisquam at suscipit sed veritatis quae sit libero harum!
            Temporibus rerum ipsam fugiat vel deleniti, iusto tempora in at modi. Dolor officiis ex, molestiae, earum officia sapiente, neque voluptate quaerat rem quisquam quasi amet repudiandae exercitationem quis voluptates. Quam.
            Possimus deserunt, esse unde aut aperiam optio modi sapiente quae, perspiciatis, eligendi suscipit veritatis. Totam repellat ipsa reiciendis incidunt cupiditate, delectus hic laudantium soluta. Officia maiores accusantium ullam eos neque.
            Vitae debitis reprehenderit aliquid ut facilis voluptatum iusto porro nobis qui omnis. Soluta similique repellat laudantium, asperiores commodi voluptatibus tempora ipsa culpa laborum, dolores a minus unde aut vitae molestiae?
            Eum, dolorum voluptatum quae sunt, mollitia cupiditate eius sed earum atque doloribus est repellendus dolore in possimus! Iure dolor deleniti excepturi asperiores modi explicabo distinctio atque saepe placeat, necessitatibus nobis.
            Pariatur delectus tempora repellendus reprehenderit, distinctio aut exercitationem ipsam saepe eveniet voluptatem dolorum iusto quaerat aliquam fugiat maiores aspernatur! Odit qui optio autem quae laborum placeat vero, repudiandae tempora voluptates.
            Deserunt quasi facere fuga natus eum? Ea adipisci culpa ab animi asperiores dolores voluptatum sed, eos at dolorem dicta pariatur eligendi, fuga maxime hic inventore natus quibusdam saepe qui aspernatur.
            Laudantium minus ullam quisquam, vel, quis rerum obcaecati dignissimos sapiente autem ea est quasi dolorum deleniti, commodi a ex ipsa nihil fugiat aut. Pariatur illum praesentium minus repellendus impedit? Nam.
            Commodi corporis veritatis at officia dolores, iusto temporibus quos sed accusamus ea dolore libero. Qui doloribus asperiores magni distinctio, quidem quod deserunt error, at minus possimus odio temporibus vel minima.
            Quidem sint facere ducimus officia? Voluptatibus eaque accusantium eius nisi odio consequuntur possimus cumque dignissimos deserunt impedit alias rerum beatae officiis hic iusto esse ullam sint, aliquid sunt repellat quia.
            Ratione nulla officiis autem blanditiis sit, consectetur repudiandae est nostrum tempore odio aperiam aliquam incidunt maxime velit ullam magni deserunt et, quidem molestiae fugit tenetur asperiores non quibusdam. Fugit, sunt.
            Minima cumque nemo magnam perferendis, consequuntur at quod impedit cum accusamus quibusdam quis. Veniam reprehenderit voluptas odio nostrum laborum, culpa cupiditate aliquam quas totam excepturi deserunt esse id et consectetur.
            Architecto repudiandae consequatur cupiditate. Necessitatibus ab dolor libero dolorem odio asperiores voluptate quos laborum veniam voluptas sint repellat excepturi iure delectus cupiditate nulla commodi nisi, blanditiis quas facere accusamus perferendis!
            Recusandae officiis in ratione repellat nisi, maiores explicabo, aliquam architecto iusto impedit quaerat eaque eos! Ab ex tempore dolorum ullam minima, ratione delectus quaerat autem asperiores hic fuga excepturi eaque.
            Quo harum accusamus cum accusantium recusandae aperiam vitae, iste reiciendis molestias a amet quam minus molestiae voluptates autem consectetur itaque repudiandae animi ratione. Voluptatibus dolorem temporibus nam, omnis repellat odit!
            Similique ipsam quis aut voluptatum velit tempore at dolorum laborum a facilis, iste animi id ipsum distinctio officia qui neque, modi, rem porro quaerat delectus iure. Similique ipsam assumenda eos!
            Eius illum, libero atque fugit distinctio ratione rem, exercitationem dicta cum, error dolorem nesciunt laborum quasi explicabo. Ullam laborum saepe, aperiam harum eligendi quia tenetur rerum quisquam distinctio dolorum error?
            Mollitia provident voluptatum qui aliquam cumque exercitationem quos totam quae corporis, quis excepturi veniam impedit repellat laborum repudiandae fuga? Fuga ipsa molestiae minus provident modi deserunt repellendus nobis magnam ratione.
            Sequi eligendi provident natus culpa eos numquam non labore dolor vitae, consequatur cupiditate impedit nobis harum iste tempore nisi, praesentium possimus adipisci repudiandae ipsa necessitatibus obcaecati! Quaerat nesciunt magnam dolorum.
            Iusto odit assumenda accusamus enim sunt. Distinctio, delectus quae. Dignissimos odit debitis id sint veritatis unde asperiores recusandae praesentium error voluptatibus deleniti, ullam ex quia et consequuntur maxime obcaecati fugit.
            Beatae voluptas corrupti nostrum ratione! Eaque quam, eos aperiam, sunt nobis asperiores error maxime corrupti sed temporibus quasi consequatur facilis illo exercitationem ex minus nesciunt culpa. Ipsa dolores corrupti adipisci.
            Cupiditate labore explicabo nisi itaque perspiciatis numquam harum possimus sequi culpa, dolore quis, nostrum sed quasi eum, expedita ea vero? Itaque iure voluptatem corporis quas, ullam delectus sequi blanditiis temporibus.
            Commodi, inventore? Repellat et magni quibusdam est, maxime doloremque nihil numquam non eos a ut. Consequatur architecto ipsum dignissimos quae suscipit quos odio magnam vitae voluptates. Illum expedita voluptatem libero.
            Ducimus aperiam, repellat sunt alias molestias animi, neque minus debitis necessitatibus in ut magni corrupti tenetur inventore, ad cumque ipsam dolor tempore? Dolor nobis ullam amet autem qui expedita impedit.
            Illo accusamus voluptatibus dolore enim tenetur eos aut impedit cumque hic laborum fugit, assumenda officia quaerat repellat architecto soluta sunt odit nihil modi adipisci laudantium fuga aspernatur nobis perferendis. Nemo!
            Deleniti recusandae dolorum nobis ipsam eos, at maxime veritatis vel consectetur explicabo fugit aspernatur dicta fuga temporibus labore sed. Nam ipsam fuga deleniti ratione quod ut aspernatur facilis odit quaerat?
            Facere aut illum cumque nihil accusantium natus eos ipsa, deleniti, repellendus ex iure debitis maxime, eum in alias nam praesentium aperiam culpa laborum et quae fugiat. Possimus sequi quam quasi.
            Sit cupiditate beatae omnis voluptas corporis debitis soluta voluptate, iure fugiat quasi similique voluptatum quibusdam ex quaerat, officia error animi enim assumenda quidem laborum. Aut dolore tenetur quis labore ratione.
            Magnam nesciunt architecto rerum voluptates libero natus, dolorem dolorum sit blanditiis qui nisi quae quisquam aliquam optio at, voluptas nemo laudantium consequuntur ducimus eius odit reprehenderit placeat laborum! Fugit, sunt!
            Odio corrupti hic blanditiis, dignissimos ipsa aliquam, atque alias at dicta eligendi repellendus ipsam, veniam enim delectus excepturi quos aperiam obcaecati voluptatum quae doloremque dolores deleniti omnis! Corrupti, recusandae molestias?
            Dolores exercitationem sed beatae nisi. Temporibus nesciunt, totam rem laboriosam earum nostrum aspernatur, odio itaque inventore molestiae assumenda voluptates id facilis perspiciatis eos ea! Mollitia corporis eveniet ullam dolorum quas?
            Minus, est! Id dicta consequatur architecto dolor quisquam ex est enim, dolorum sequi error hic! Distinctio voluptas incidunt cupiditate nesciunt dolorem quam iste sequi, aspernatur adipisci voluptate repudiandae, et excepturi.
            Vitae et aliquid aspernatur, ducimus perferendis ad error nihil quis sint quam commodi unde. Enim provident quos quas! Excepturi, quaerat tenetur illo esse architecto et repudiandae ratione iure? Cum, expedita.
            Dolor voluptas, totam optio dignissimos nobis officia quae adipisci. Deserunt nulla saepe numquam iste excepturi omnis debitis a nemo? Neque sint temporibus quisquam amet veritatis nobis fugiat doloremque at dolores.
            Doloribus quasi quis expedita nihil laborum fuga alias eligendi earum consequatur repudiandae, officia exercitationem consequuntur dolores quas. Expedita, veritatis facilis. Quo, minus perspiciatis. Repellendus, debitis aspernatur dicta molestiae omnis architecto?
            Quas minus sint dicta numquam esse delectus a at eos. Vel iusto officiis incidunt, ipsam sunt repellat necessitatibus id illo ad quia placeat exercitationem, dolores saepe odio impedit deleniti porro.
            Sapiente voluptatibus blanditiis dolores ad, dicta, eum saepe similique quia fugiat optio culpa reprehenderit iusto aspernatur deserunt quidem? Nulla odio magni mollitia illum quis. Recusandae sequi quod ab accusantium neque.
            Soluta maxime nesciunt, impedit veniam officiis omnis voluptate voluptatum quis sequi, necessitatibus modi voluptates excepturi cum odio animi provident magni dicta pariatur nostrum id. Dolores quisquam molestias cupiditate vero maiores.
            Repudiandae impedit et nulla itaque aliquid? Praesentium error non dolorem iste accusantium et quis eum aliquam illo voluptatibus porro esse, reiciendis ex vitae ratione tenetur minus voluptatem rem nesciunt sint.
            Omnis, repellendus explicabo. Voluptatem officia adipisci maiores porro incidunt dolores! A, non omnis magni, exercitationem quae saepe labore accusantium officia libero quo sint, hic dignissimos ipsam quisquam neque ad aliquam!
            Doloremque praesentium, ullam odit nesciunt nihil sequi consequatur ex quisquam vitae mollitia. Optio quo iusto temporibus porro quam, hic aspernatur, voluptatem beatae ea provident adipisci error earum reiciendis unde maxime!
            Eos sapiente quidem recusandae inventore quo temporibus ipsum. Deleniti numquam aperiam rerum similique harum a itaque? Aut, illum. Consequuntur pariatur laborum id voluptas nesciunt repellat veniam rem, nihil sit sapiente.
            Enim distinctio doloribus architecto? Sint quas laborum voluptatem optio tenetur fugit mollitia, doloremque saepe ipsa explicabo officiis neque molestiae consequatur sapiente cupiditate provident nostrum quia vero ipsum molestias reprehenderit excepturi!
            Placeat incidunt repudiandae animi quae optio accusamus architecto totam, corporis, voluptatibus, assumenda aliquam exercitationem veniam sit ex dolorem voluptates voluptatum culpa repellat impedit molestiae pariatur adipisci eum explicabo modi. Error.
            Quia nesciunt sint explicabo earum unde praesentium quibusdam, ipsam veritatis. Beatae, dicta ex vero nemo sequi ipsum cum. Molestiae accusamus voluptates nostrum consequatur quas quos at architecto nihil quidem distinctio!
            Quia quam odio vero placeat. Nostrum similique, ducimus quidem dolores eligendi ipsam veniam ipsa quas debitis eius hic omnis laboriosam, perferendis est dolore vel labore. Itaque animi dignissimos ipsa autem?
            Laudantium dolores consequatur minima voluptates ipsum at harum totam. Atque voluptates dignissimos culpa ex eveniet optio. Placeat iusto hic minima illum iure nobis. Consequuntur dolor dolorem pariatur, alias tempore dolores.
            Id tenetur sunt unde illo quas, non repellat nulla, maxime delectus magnam ab molestias? Voluptatem, pariatur asperiores repudiandae impedit tempore nesciunt molestias vel enim fuga earum. Tempore numquam fugit libero!
            Reiciendis laudantium tempore nesciunt natus ipsum sunt iure accusamus, iste consequatur ullam autem quos libero. Officiis, earum vero iusto reiciendis provident expedita ex nam ducimus voluptatem veritatis eveniet tempora assumenda.
            Dicta reiciendis ipsa non debitis autem, eius quam voluptate corporis, maiores pariatur adipisci ipsam eum labore veniam nulla quibusdam praesentium. Odit, eum nulla laboriosam blanditiis iure repudiandae alias nobis. Excepturi.
            Repellat rem odit deleniti quia, doloribus repellendus dicta earum exercitationem! Asperiores expedita facere voluptatibus fugit nobis ullam voluptas! Nostrum repudiandae aliquam quas doloremque, iure ipsam nam amet nulla possimus incidunt.
            Iure praesentium, ut ea illo nisi iste asperiores similique corporis rerum sit. Sequi, velit quam aliquid sunt ipsam officia voluptatem repellat atque minus eius iure. Porro ullam doloribus culpa repudiandae.
            Ea molestias fugiat nulla dicta eum natus! Sequi repellendus laudantium quibusdam quam, laborum at quasi ipsam debitis ipsa quaerat non fuga corrupti animi veritatis neque minima obcaecati inventore eaque eum?
            Aliquid commodi soluta omnis recusandae ad nesciunt magni nisi doloremque placeat saepe, dicta libero ipsa assumenda quo totam. Repellat, harum saepe voluptatibus molestias nobis illo blanditiis mollitia consectetur dicta aut.
            Obcaecati vitae error ut tempore. Autem possimus eveniet vitae tempore sint sequi error velit quo laborum. Maiores itaque debitis voluptates doloribus beatae voluptatum architecto pariatur! Dolorum adipisci possimus id esse!
            Maxime consequuntur eos accusantium eligendi cumque minima illo aut, laudantium pariatur natus tempore, eveniet odit consequatur assumenda neque fugiat sit earum ullam nihil nulla at expedita, recusandae tempora. Esse, amet.
            Veritatis quos cupiditate harum soluta ea quibusdam consectetur a officia beatae quia laboriosam voluptates unde perspiciatis numquam aspernatur velit iusto in excepturi dolorum, delectus tenetur. Fugiat sit libero possimus laboriosam.
            Ipsum nam incidunt quis provident deserunt, eum magni at corporis aliquid eos culpa beatae, itaque enim quasi saepe qui fuga? Quos porro commodi ratione harum esse voluptatum impedit asperiores doloremque?
            Vero quaerat dolore aut suscipit laudantium, temporibus eveniet soluta rem neque. Vero aliquid obcaecati numquam molestias tenetur, impedit laborum totam explicabo sapiente laudantium assumenda excepturi. Modi consectetur quibusdam est natus!
            Earum voluptatum harum corrupti. Illo, sequi molestiae et sapiente ad dicta est tempore quidem neque, vitae quo corporis ratione reiciendis, quia libero cum cupiditate sit laborum sint voluptate quaerat. Ad.
            Quae ab blanditiis commodi assumenda est provident, voluptatum nihil necessitatibus, illum molestias error architecto voluptate earum vel veniam quos quod aliquam optio eum sed sequi quis iusto recusandae in! Dolorum?
            Ipsa ad velit porro corrupti, cupiditate blanditiis delectus vel illum unde laudantium expedita facere quas commodi pariatur illo a optio harum laborum sit ducimus nemo quos reiciendis iusto dolor. Sapiente.
            Excepturi, ipsum. Ratione quia eaque totam doloribus deleniti labore iusto tempora, necessitatibus praesentium ipsam! Error reiciendis accusantium explicabo temporibus suscipit, incidunt perferendis sit odit qui aliquam, illum rerum, magni impedit.
            Porro, eos fugit dolore ipsam pariatur voluptates ex! Nam debitis ex aliquam perferendis fugiat sit, dicta asperiores doloribus, sint officiis, ad temporibus numquam vel repudiandae soluta nesciunt error placeat eos?
            Tempore eaque possimus nemo, ratione inventore voluptates. Consectetur minus at eaque quod quasi aspernatur, maxime impedit vel ea asperiores sapiente, molestias ullam distinctio! Voluptatum quibusdam iure, optio corrupti nulla quidem.
            Blanditiis quisquam earum omnis fugit fuga necessitatibus totam atque iure! Sapiente animi impedit voluptatum id eius et mollitia blanditiis est aspernatur quibusdam, nulla exercitationem magni ducimus ullam quod tenetur perspiciatis?
            Sed architecto illum molestias doloremque, nulla, numquam iste error ad excepturi, magni rerum sint nam fugiat. Tempora maiores nulla, minima id officiis, earum officia modi aspernatur quas aliquid suscipit ratione?
            Optio, voluptas quos. Deleniti voluptate omnis dolorem sit sapiente tenetur consequuntur alias, neque voluptatem voluptas impedit amet libero sunt sint accusamus nostrum repudiandae consequatur saepe dignissimos atque magni odit! Suscipit.
        </Text>
    );
}

export default FavoriteScreen;